# Generated by Django 5.2.6 on 2025-09-20 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='profissao',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
