# Generated by Django 5.2.6 on 2025-09-21 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_person_profissao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='birthday',
        ),
    ]
