# Generated by Django 5.2.6 on 2025-09-21 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_remove_person_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='email_id',
        ),
        migrations.RemoveField(
            model_name='person',
            name='profissao',
        ),
        migrations.AddField(
            model_name='person',
            name='atuacao_especialidade',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='breve_descricao_apresentacao',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.CharField(max_length=320, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='localizacao',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='servicos_oferecidos',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='watzapp',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
