# Generated by Django 5.2.6 on 2025-09-21 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_remove_person_email_id_remove_person_profissao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='email_id',
            field=models.CharField(max_length=320, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profissao',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
