# Generated by Django 5.2.6 on 2025-09-24 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_person_email_id_person_profissao'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='facebook',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='instagram',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
